# Generated by Django 3.2.5 on 2021-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='F192A5', editable=False, max_length=100),
        ),
    ]
