# Generated by Django 3.2.4 on 2021-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0002_alter_postarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='slug',
            field=models.CharField(default=0, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
