# Generated by Django 3.2.5 on 2021-07-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0002_alter_classroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='04FED5', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='major',
            name='year',
            field=models.ManyToManyField(to='rollcall.Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to='rollcall.usernew'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to='rollcall.usernew'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernew',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
