# Generated by Django 3.2.4 on 2021-07-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0002_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='F6A97B23', editable=False, max_length=10, unique=True),
        ),
    ]
