# Generated by Django 3.2.4 on 2021-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0003_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='5BDD88AA', editable=False, max_length=10, unique=True),
        ),
    ]
