# Generated by Django 3.2.5 on 2021-07-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0003_auto_20210720_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='F4DCD8', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
