# Generated by Django 3.2.4 on 2021-07-25 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0003_alter_postarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
