# Generated by Django 3.2.4 on 2021-07-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0004_alter_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='roomQr/'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
