# Generated by Django 3.2.4 on 2021-07-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0004_alter_postarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
