# Generated by Django 3.2.4 on 2021-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0005_auto_20210724_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='roomQr/'),
        ),
    ]
